name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.5.0

      - name: Installing dart_frog CLI
        run: dart pub global activate dart_frog_cli

      - name: Fetching dependencies
        run: dart pub get

      - name: Building the application
        run: dart_frog build

      - name: ls ing the file
        run: ls

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Loggin into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./build/Dockerfile
          push: true
          tags: shamansharif/prayer-time-api:latest
